version: '3.6'

services: 
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    restart: always
    depends_on:
      - db
    ports: 
      - '21061:21061'
    volumes: 
      - .:/usr/app

  db:
    container_name: 'database-node'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports: 
      - '3308:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    volumes:
      - ./init:/docker-entrypoint-initdb.d
